core/urls.py
from django.urls import path, include
from .views import index, cadastro,logout
from django.contrib.auth import views
from .forms import LoginForm

urlpatterns = [
    path('login/',  views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('cadastro/', cadastro, name='cadastro'),
    path('logout/', logout, name='logout'),
    path('', index, name='index')
]

newItem/urls.py
from django.urls import path
from .views import CadastroNovoCarro, Detalhes

app_name = 'carro'

urlpatterns = [
    path('novo_carro/', CadastroNovoCarro, name="novo_carro"),
    path('detalhes/<uuid:id>/', Detalhes, name='detalhes')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('newItem/', include('newItem.urls')),
    path('dashboard/', include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django import forms


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Seu Usuário','class': 'w-full py-4 px-6 rounded-xl'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Seu Usuário','class': 'w-full py-4 px-6 rounded-xl'}))


class CadastroForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
    
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Seu Usuário', 'class': 'w-full py-4 px-6 rounded-xl'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'Seu E-mail','class': 'w-full py-4 px-6 rounded-xl'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Seu Nome','class': 'w-full py-4 px-6 rounded-xl'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Seu Sobrenome','class': 'w-full py-4 px-6 rounded-xl'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Sua Senha','class': 'w-full py-4 px-6 rounded-xl'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Digite Sua Senha Novamente','class': 'w-full py-4 px-6 rounded-xl'}))

    def clean(self):
        cleade =  super().clean()
        password1 = cleade.get("password1")
        password2 = cleade.get("password2")

        print(password1, password2)
        return cleade
    
class FiltroMarcaForm(forms.Form):
    Pesquisa = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Busque aqui..', 'class': 'w-1/2 py-4 px-6 rounded-xl mb-8 bg-gray-100'}))

core/views.py
from django.shortcuts import render, redirect
from .forms import CadastroForm, FiltroMarcaForm
from newItem.models import Carro
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout


@login_required
def index(request):
    form = FiltroMarcaForm(request.GET or None)
    item = Carro.objects.all()
    if form.is_valid():
        marca = form.cleaned_data.get('Pesquisa')
        if marca:
            item = item.filter(nome__icontains=marca)
            
    items_agrupado = (item.values('marca_carro__marca_carro').annotate(count=Count('marca_carro')).order_by('marca_carro__marca_carro'))
    print(items_agrupado)
    context = {
        'item': item,
        'form': form,
        'items_agrupado': items_agrupado
    }
    return render(request, "core/index.html", context)

def login(request):
    print(request.user)
    return render(request, "core/login.html")

def logout(request):
    auth_logout(request)
    return redirect('login')

def cadastro(request):
    if request.method == "POST":
        form = CadastroForm(request.POST)
        if form.is_valid():
            form.save()
            print("Correto")
            return redirect('login')
        else:
            print(form.error_messages)
    else:
        form = CadastroForm()
    context = {'form': form}
    return render(request, 'core/cadastro.html', context)

core/templates/core/cadastro.html
{%extends '_base.html'%}
<title>{%block title%} Cadastro {%endblock title%}</title>
{%block content%}
<section class="my-6 p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Cadastro</h1>
    <div>
        <form method="post">
            {%csrf_token%}
            <div class="mb-3">
                <label for="username">Usuário</label>
                {{form.username}}
            </div>
            
            <div class="mb-3">
                <label for="email">E-mail</label>
                {{form.email}}
            </div>
            
            <div class="mb-3">
                <label for="nome">Seu Nome</label>
                {{form.first_name}}
            </div>

            
            <div class="mb-3">
                <label for="sobrenome">Seu Sobrenome</label>
                {{form.last_name}}
            </div>
            
            <div class="mb-3">
                <label for="password">Senha</label>
                {{form.password1}}
            </div>

            <div class="mb-3">
                <label for="password">Senha</label>
                {{form.password2}}
            </div>

            <button type="submit" class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Enviar</button>
        </form>
    </div>
</section>
{%endblock content%}

core/templates/core/index.html
{%extends '_base.html'%}

<title>{%block title%} Inicio {%endblock title%}</title>
{%block content%}
<section class="py-10">
    <div class="container mx-auto mb-8 text-center">
        <form method="get" class="mb-4">
            {{form.as_p}}
            <button type="submit" class="bg-teal-500 text-white px-4 py-2 rounded hover:bg-teal-700">Filtrar</button>
        </form>
    </div>
    <h2 class="text-2xl text-center mb-6 tracking-wide">Ofertas Disponivéis</h2>
    <div class="container mx-auto px-6 py-6">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
            {%for i in item%}
            <a href="{% url 'carro:detalhes' i.id %}">
                <figure
                    class="bg-gray-100 rounded-xl border px-6 py-8 w-full hover:bg-gray-400 transition duration-150 ease-in-out -translate-y-6">
                    <img src="{{i.imagem.url}}" alt="{{i.nome}}"
                        class="w-full h-48 object-center rounded-t-lg hover:scale-105 transition duration-150 ease-in-out">

                    <figcaption class="text-2xl text-center font-bold-200 py-2">
                        {{i.nome}}
                    </figcaption>
                </figure>
            </a>
            {%endfor%}
        </div>
    </div>

    <div class="mt-12 px-6 py-8 bg-gray-100 rounded-xl text-center">
        <h2 class="mb-12 text-2xl">Marcas</h2>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
            {%for i in items_agrupado %}
            <div class="p-6 bg-white rounded-b-xl">
                <p class="text-2xl">{{i.marca_carro__marca_carro}}</p>
                <p class="text-lg">{{i.count}} itens</p>
            </div>
            {%endfor%}
        </div>
    </div>
</section>
{%endblock content%}

core/templates/core/login.html
{%extends '_base.html'%}
<title>{%block title%} Login {%endblock title%}</title>

{%block content%}
<div class="my-6 p-6 bg-gray-100 rounded-xl p-6">
    <h1 class="mb-6 text-3xl">Login</h1>
    <form method="post">
        {% csrf_token %}


        <div class="mb-3">
            <label class="inline-block mb-2">Usuário</label><br>
            {{form.username}}
        </div>

        
        <div class="mb-3">
            <label class="inline-block mb-2">Senha</label><br>
            {{form.password}}
        </div>


        <button type="submit" class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Enviar</button>
    </form>

</div>
{%endblock content%}