core/urls.py
from django.urls import path, include
from .views import index, cadastro,logout
from django.contrib.auth import views
from .forms import LoginForm

urlpatterns = [
    path('login/',  views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('cadastro/', cadastro, name='cadastro'),
    path('logout/', logout, name='logout'),
    path('', index, name='index')
]

dashboard/urls.py
from django.urls import path
from .views import dashboard, editar, delete

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('editar/<uuid:id>/', editar, name='editar'),
    path('delete/<uuid:id>/', delete, name='delete')
]

newItem/urls.py
from django.urls import path
from .views import CadastroNovoCarro, Detalhes

app_name = 'carro'

urlpatterns = [
    path('novo_carro/', CadastroNovoCarro, name="novo_carro"),
    path('detalhes/<uuid:id>/', Detalhes, name='detalhes')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('newItem/', include('newItem.urls')),
    path('dashboard/', include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django import forms


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Seu Usuário','class': 'w-full py-4 px-6 rounded-xl'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Seu Usuário','class': 'w-full py-4 px-6 rounded-xl'}))


class CadastroForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
    
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Seu Usuário', 'class': 'w-full py-4 px-6 rounded-xl'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'Seu E-mail','class': 'w-full py-4 px-6 rounded-xl'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Seu Nome','class': 'w-full py-4 px-6 rounded-xl'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Seu Sobrenome','class': 'w-full py-4 px-6 rounded-xl'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Sua Senha','class': 'w-full py-4 px-6 rounded-xl'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Digite Sua Senha Novamente','class': 'w-full py-4 px-6 rounded-xl'}))

    def clean(self):
        cleade =  super().clean()
        password1 = cleade.get("password1")
        password2 = cleade.get("password2")

        print(password1, password2)
        return cleade
    
class FiltroMarcaForm(forms.Form):
    Pesquisa = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Busque aqui..', 'class': 'w-1/2 py-4 px-6 rounded-xl mb-8 bg-gray-100'}))

core/views.py
from django.shortcuts import render, redirect
from .forms import CadastroForm, FiltroMarcaForm
from newItem.models import Carro
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout


@login_required
def index(request):
    form = FiltroMarcaForm(request.GET or None)
    item = Carro.objects.all()
    if form.is_valid():
        marca = form.cleaned_data.get('Pesquisa')
        if marca:
            item = item.filter(nome__icontains=marca)
            
    items_agrupado = (item.values('marca_carro__marca_carro').annotate(count=Count('marca_carro')).order_by('marca_carro__marca_carro'))
    print(items_agrupado)
    context = {
        'item': item,
        'form': form,
        'items_agrupado': items_agrupado
    }
    return render(request, "core/index.html", context)

def login(request):
    print(request.user)
    return render(request, "core/login.html")

def logout(request):
    auth_logout(request)
    return redirect('login')

def cadastro(request):
    if request.method == "POST":
        form = CadastroForm(request.POST)
        if form.is_valid():
            form.save()
            print("Correto")
            return redirect('login')
        else:
            print(form.error_messages)
    else:
        form = CadastroForm()
    context = {'form': form}
    return render(request, 'core/cadastro.html', context)

core/templates/_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>{%block title%} {%endblock title%} | Gestão</title>
</head>

<body>
    <nav class="flex justify-between items-center px-6 py-6 bg-gray-200">

        <a href="{% url 'index' %}">
            <p class="text-2xl font-semibold">{%if request.user.is_authenticated%}Olá, {{request.user}} {%else%} KNIB {%endif%}</p>
        </a>

        {%if request.user.is_authenticated%}
        <div class="flex space-x-6 text-center">
            <a href="{% url 'dashboard:dashboard' %}">
                <p class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Dashboard</p>
            </a>
            <a href="{% url  'carro:novo_carro'%}">
                <p class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Novo Carro</p>
            </a>
            <a href="{% url 'logout' %}">
                <p class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Logout
                </p>
            </a>
        </div>
        {%else%}
        <div class="flex space-x-6 text-center">
            <a href="{%url 'login'%}">
                <p class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Login</p>
            </a>
            <a href="{% url 'cadastro' %}">
                <p class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Cadastro
                </p>
            </a>
        </div>
        {%endif%}
        
    </nav>
    <main class="container px-6 py-6 mx-auto">
        {%include '_message.html' %}
        {%block content%}
        {%endblock content%}
    </main>

    <footer class="px-6 py-6 flex justify-between bg-gray-200 h-80 mt-10">
        <div class="flex flex-col justify-center items-center">
            <h2 class="text-lg">Made In Brazil</h2>
            <div class="w-2/3">
                <h3 class="mb-5 font-semibold ">About</h3>

                <p class="text-lg mb-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia est
                    quidem
                    nisi repellendus esse non vitae consequuntur harum cumque hic! Earum consequuntur velit totam minus
                    sint
                    itaque laborum id quaerat?</p>
            </div>
        </div>
    </footer>
</body>

</html>

core/templates/_message.html
{%if form.errors or form.non_field_errors%}
<div class="mb-3 p-6 bg-red-100 rounded-xl">
    {%for field in form%}
    {{field.errors}}
    {%endfor%}

    {{form.non_field_errors}}
</div>
{%endif%}


{% if messages %}
<ul>
    {% for message in messages %}
    {%if message.tags == "success"%}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {%else%}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {%endif%}
    {% endfor %}
</ul>
{% endif %}