core/urls.py
from django.urls import path, include
from .views import index, cadastro,logout
from django.contrib.auth import views
from .forms import LoginForm

urlpatterns = [
    path('login/',  views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('cadastro/', cadastro, name='cadastro'),
    path('logout/', logout, name='logout'),
    path('', index, name='index')
]

dashboard/urls.py
from django.urls import path
from .views import dashboard, editar, delete

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('editar/<uuid:id>/', editar, name='editar'),
    path('delete/<uuid:id>/', delete, name='delete')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('newItem/', include('newItem.urls')),
    path('dashboard/', include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from newItem.models import Carro


class editarCarroForm(forms.ModelForm):
    class Meta:
        model = Carro
        fields = ("nome", "chassi", "marca_carro", "cor", "preco", "tipo_combustivel", "ano", 'imagem')
        widgets = {
            "nome": forms.TextInput(attrs={
                'class': "w-full py-4 px-6 rounded-xl border"
            }),
            "chassi": forms.TextInput(attrs={
                'class': "w-full py-4 px-6 rounded-xl border"
            }),
            "marca_carro": forms.Select(attrs={
                'class': "w-full py-4 px-6 rounded-xl border"
            }),
            "cor": forms.TextInput(attrs={
                'class': "w-full py-4 px-6 rounded-xl border"
            }),
            "preco":forms.TextInput(attrs={
                'class': "w-full py-4 px-6 rounded-xl border"
            }),
            "tipo_combustivel": forms.Select(attrs={
                'class': "w-full py-4 px-6 rounded-xl border"
            }),
            "ano":forms.NumberInput(attrs={
                'class': "w-full py-4 px-6 rounded-xl border"
            }),
            "imagem":forms.FileInput(attrs={
                'class': "w-full py-4 px-6 rounded-xl border"
            }),
        }

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from newItem.models import Carro
from django.contrib import messages
from .forms import editarCarroForm


@login_required
def dashboard(request):
    item = Carro.objects.filter(criado_por = request.user).first()
    context = {
        'item': item
    }
    return render(request, 'dashboard.html', context)


@login_required
def editar(request, id):
    item = Carro.objects.get(id=id)
    if request.method == "POST":
        form = editarCarroForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()
            messages.success(request, 'Item Editado com sucesso')
            return redirect("dashboard:dashboard")
    else:
        form = editarCarroForm(instance=item)
    
    context = {
        'form': form
    }
    return render(request, 'formsEditar.html', context)

@login_required
def delete(request, id):
    item = Carro.objects.get(id=id)
    if item:
        item.delete()
        messages.success(request, 'Excluido com sucesso')
    else:
        messages.error(request, 'Erro ao Excluir')
    return redirect("dashboard:dashboard")
        

dashboard/templates/dashboard.html
{%extends '_base.html'%}

{%block title%} Dashboard {%endblock title%}

{%block content%}
{%if item%}
<section class="my-20 md:my-1 bg-gray-100">
    <div class="flex flex-col justify-center items-center border-2 text-center py-8 px-6 rounded-xl">
        {%if item.imagem%}
        <figure class="flex flex-row justify-center gap-x-8 items-center">
            <img src="{{item.imagem.url}}" alt="{{imagem.nome}}" class="rounded-lg w-1/2 shadow-lg shadow-white">
            <figcaption>
                <ul class="text-center">
                    <li class="mb-6 text-lg text-white bg-teal-500 px-6 py-6 rounded-xl">Nome: {{item.nome}}</li>
                    <li class="mb-6 text-lg text-white bg-teal-500 px-6 py-6 rounded-xl">Marca: {{item.marca_carro}}</li>
                    <li class="mb-6 text-lg text-white bg-teal-500 px-6 py-6 rounded-xl">Cor: {{item.cor}}</li>
                    <li class="mb-6 text-lg text-white bg-teal-500 px-6 py-6 rounded-xl">Combustivel: {{item.tipo_combustivel}}</li>
                    <li class="mb-6 text-lg text-white bg-teal-500 px-6 py-6 rounded-xl">Preço:{{item.preco_formatado}}</li>
                </ul>
            </figcaption>
        </figure>

        <div class="my-8">
            <a href="{% url 'dashboard:editar' item.id %}"><button type="submit"
                    class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Editar</button></a>
            <a href="{% url 'dashboard:delete' item.id %}"><button type="submit"
                    class="py-4 px-8 text-lg bg-red-500 hover:bg-red-700 rounded-xl text-white">Deletar</button></a>
        </div>
        {%endif%}
    </div>
</section>
{%else%}
<section class="container mx-auto">
    <div class="mt-8 text-center bg-teal-700 rounded-xl px-8 py-8">
        <h1 class="text-2xl text-white">Sem Items</h1>
    </div>
</section>
{%endif%}
{%endblock content%}

dashboard/templates/formsEditar.html
{%extends '_base.html'%}

{%block title%}Editar Carro{%endblock title%}

{%block content%}
<section>
    <h1 class="mb-6 text-3xl">Editar Carro</h1>

    {%include "_message.html" %}
    <form method="post" enctype="multipart/form-data">
        {%csrf_token%}

        <div class="space-x-3">
            {{form.as_p}}
        </div>
        <button type="submit" class="py-4 mt-5 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Enviar</button>
    </form>

</section>
{%endblock content%}